spring.datasource.url=jdbc:mysql://semo-db-cloud-nnta.e.aivencloud.com:24154/semo_db?useSSL=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=avnadmin

spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh

server.port = ${Port}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# File Upload Configuration
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB